import pandas
import requests
import normalizer

def get_person(name, session, BASE_URL):
    # Get's person via normalized RDF id
    # We're using plone.i18n to match id generated by Plone
    person_id = normalizer.baseNormalize(name)
    url = BASE_URL + 'persons/' + person_id

    response = session.get(url)

    if response.json()["@type"]:
        return response.json()

def get_org(name, session, BASE_URL):
    # Get's org via normalized RDF id
    # We're using plone.i18n to match id generated by Plone
    org_id = normalizer.baseNormalize(name)
    url = BASE_URL + 'organizations/' + org_id

    response = session.get(url)

    if response.json()["@type"]:
        return response.json()


# Setup authenticated session
# https://plonerestapi.readthedocs.io/en/latest/authentication.html

BASE_URL = "http://localhost:8080/weviz/"

session = requests.Session()
session.auth = ('', '')
session.headers.update({'Accept': 'application/json'})

# Import Dataframe
# This script uses Pandas library to handle import of spreadsheet data,
# including clean up operations
# https://pandas.pydata.org/pandas-docs/stable/getting_started/index.html

df_persons = pandas.read_excel('source/PEPs Data Samples.xlsx',
                               sheet_name='Person')

df_organizations = pandas.read_excel('source/PEPs Data Samples.xlsx',
                                     sheet_name='Organization')

df_memberships = pandas.read_excel('source/PEPs Data Samples.xlsx',
                                   sheet_name='Membership')

# import persons
for index, person in df_persons.iterrows():

    pkg = {}
    pkg['@type'] = 'Person'
    pkg['name'] = person['id']

    if person['gender'] == 'ชาย':
        pkg['gender'] = {'token': 'male', 'title': 'Male'}
    else:
        pkg['gender'] = {'token': 'female', 'title': 'Female'}

    pkg['summary'] = "NULL"
    print(pkg['name'])
    response = session.post(BASE_URL + 'persons/', json=pkg)
    print(response)

# # import organisations
for index, org in df_organizations.iterrows():
    pkg = {}
    pkg['@type'] = 'Organization'
    pkg['name'] = org['id']
    print(pkg['name'])
    response = session.post(BASE_URL + 'organizations/', json=pkg)
    print(response)

# import membership

for index, member in df_memberships.iterrows():
    person = get_person(member['person_id'], session, BASE_URL)
    org = get_org(member['organization_id'], session, BASE_URL)

    pkg = {}
    pkg['@type'] = "Membership"
    pkg['label'] = member['label']
    pkg['role'] = member['role']
    pkg['organization'] = org['@id']
    pkg['person'] = person['@id']
    session.post(org['@id'], json=pkg)
